littleblog/blueprints/home.py
"""
Exports home routes.
"""

from flask import Blueprint, render_template

home = Blueprint('home', __name__, url_prefix='/')

@home.route('/')
def index():
    """
    Index route.
    """

    return render_template('home/index.html')

littleblog/blueprints/post.py
"""
Exports post routes.
"""

from datetime import datetime

from flask import (Blueprint,
                   flash,
                   jsonify,
                   redirect,
                   render_template,
                   request,
                   session,
                   url_for)

from littleblog.forms import CommentForm, PostForm
from littleblog.helpers import (author_required,
                          get_comments,
                          get_posts,
                          markdown_to_html,
                          post_required,
                          serialize,
                          sign_in_required)
from littleblog.models import Comment, Post

post = Blueprint('post', __name__, url_prefix='/post')

@post.route('/create', methods=['GET', 'POST'])
@sign_in_required
def create(current_user):
    """
    Create post route.
    """

    # parse the form
    form = PostForm(request.form, obj=Post())

    # render create post form if GET request
    if request.method == 'GET':
        return render_template('post/create.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('post/create.html', form=form), 400

    # create new post
    new_post = Post(author=current_user,
                    title=form.title.data,
                    lead_paragraph=form.lead_paragraph.data,
                    image_url=form.image_url.data,
                    content=form.content.data).save()

    # notify user
    flash('Post successfully created.', 'success')

    # redirect to post page
    return redirect(url_for('post.show', post_id=str(new_post.id)))

@post.route('/<post_id>/show', methods=['GET'])
@post_required
def show(post_id, selected_post):
    """
    Show post route.
    """

    return render_template('post/show.html',
                           form=CommentForm(),
                           post=selected_post,
                           is_author=str(selected_post.author.id) == session.get('user_id'))

@post.route('/<post_id>/settings', methods=['GET'])
@sign_in_required
@post_required
@author_required
def settings(current_user, post_id, selected_post):
    """
    Post settings route.
    """

    return render_template('post/settings.html', post=selected_post)

@post.route('/<post_id>/update', methods=['GET', 'POST'])
@sign_in_required
@post_required
@author_required
def update(current_user, post_id, selected_post):
    """
    Update post route.
    """

    # parse the form
    form = PostForm(request.form, obj=selected_post)

    # render update post form if GET request
    if request.method == 'GET':
        return render_template('post/update.html', form=form, post=selected_post)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('post/update.html', form=form, post=selected_post), 400

    # update the post information
    form.populate_obj(selected_post)
    selected_post.last_updated = datetime.now()
    selected_post.save()

    # notify the user
    flash('Post successfully updated.', 'success')

    # redirect back to post page
    return redirect(url_for('post.show', post_id=post_id))

@post.route('/<post_id>/delete', methods=['GET', 'POST'])
@sign_in_required
@post_required
@author_required
def delete(current_user, post_id, selected_post):
    """
    Delete post route.
    """

    # render delete page if GET request
    if request.method == 'GET':
        return render_template('post/delete.html', post=selected_post)

    selected_post.delete()

    # notify user
    flash('Successfully deleted post.', 'success')

    # redirect back to homepage
    return redirect(url_for('home.index'))

@post.route('/latest', methods=['GET'])
def latest():
    """
    Latest post route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for latest posts (making sure to exclude the actual content)
    results = get_posts(exclude=['content'],
                        order_by=['-created'],
                        skip=skip,
                        limit=limit)

    return jsonify(serialize(results))

@post.route('/<post_id>/comments', methods=['GET'])
@post_required
def comments(post_id, selected_post):
    """
    Post comments route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for post's comments (making sure to exclude the post itself)
    results = get_comments(post_id=post_id,
                           exclude=['post'],
                           order_by=['created'],
                           skip=skip,
                           limit=limit)

    return jsonify(serialize(results))

@post.route('/<post_id>/comment', methods=['POST'])
@sign_in_required
@post_required
def comment(current_user, post_id, selected_post):
    """
    Post comment route.
    """

    # parse the form
    form = CommentForm(request.form)

    # form is not valid so return error
    if not form.validate_on_submit():
        errors = []
        for field_name, field_errors in form.errors.items():
            for error in field_errors:
                errors.append(error)
        return jsonify({'errors': errors, 'success': False}), 400

    # create the comment
    Comment(author=current_user,
            post=selected_post,
            text=form.text.data).save()

    return jsonify({'success': True}), 200

@post.route('/preview', methods=['POST'])
def preview():
    """
    Post preview route.
    """

    return jsonify({'html': markdown_to_html(request.form.get('content', ''))}), 200

littleblog/blueprints/search.py
"""
Exports search routes.
"""

from flask import Blueprint, jsonify, render_template, request

from littleblog.helpers import request_wants_json, search_posts, serialize

search = Blueprint('search', __name__, url_prefix='/search')

@search.route('/', methods=['GET'])
def index():
    """
    Search route.
    """

    # not json so just render search page
    if not request_wants_json():
        return render_template('search/index.html')

    # get query parameters
    terms = request.args.get('terms', '', type=str)
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # search for posts (making sure to exclude the actual content)
    results = search_posts(search_text=terms,
                           exclude=['content'],
                           order_by=['$text_score'],
                           skip=skip,
                           limit=limit)

    return jsonify(serialize(results))

littleblog/blueprints/user.py
"""
Exports user routes.
"""

from flask import (Blueprint,
                   flash,
                   jsonify,
                   redirect,
                   render_template,
                   request,
                   session,
                   url_for)
from passlib.hash import sha256_crypt

from littleblog.forms import SignInForm, SignUpForm, UpdatePasswordForm, UpdateProfileForm
from littleblog.helpers import (get_posts,
                          serialize,
                          sign_in_required,
                          sign_out_required,
                          user_required)
from littleblog.models import User

user = Blueprint('user', __name__, url_prefix='/user')

"""
User routes.
"""

@user.route('/sign-up', methods=['GET', 'POST'])
@sign_out_required
def sign_up():
    """
    User sign up route.
    """

    # parse the form
    form = SignUpForm(request.form)

    # render sign up form if GET request
    if request.method == 'GET':
        return render_template('user/sign_up.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/sign_up.html', form=form), 400

    # save new user
    new_user = User(email=form.email.data,
                    password=sha256_crypt.hash(form.password.data),
                    display_name=form.display_name.data).save()

    # make sure we store user id and avatar url in session
    session['user_id'] = str(new_user.id)
    session['avatar_url'] = new_user.avatar_url

    # notify user
    flash('Profile successfully created.', 'success')

    # redirect to user's profile page
    return redirect(url_for('user.show', user_id=session['user_id']))

@user.route('/sign-in', methods=['GET', 'POST'])
@sign_out_required
def sign_in():
    """
    User sign in route.
    """

    # parse the form
    form = SignInForm(request.form)

    # render sign in form if GET request
    if request.method == 'GET':
        return render_template('user/sign_in.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/sign_in.html', form=form), 400

    # make sure we store user id and avatar url in session
    session['user_id'] = str(form.user.id)
    session['avatar_url'] = form.user.avatar_url

    # notify user
    flash('Successfully signed in.', 'success')

    # redirect to next screen (if there is one) or home page
    return redirect(request.args.get('next') or url_for('home.index'))

@user.route('/sign-out', methods=['GET', 'POST'])
def sign_out():
    """
    User sign out route.
    """

    # clear session data only if POST request
    if request.method == 'POST':
        session.clear()

    # render sign out page
    return render_template('user/sign_out.html')

@user.route('/<user_id>/show', methods=['GET'])
@user_required
def show(user_id, selected_user):
    """
    User show route.
    """

    return render_template('user/show.html', user=selected_user)

@user.route('/settings', methods=['GET'])
@sign_in_required
def settings(current_user):
    """
    User settings route.
    """

    return render_template('user/settings.html', user=current_user)

@user.route('/update-profile', methods=['GET', 'POST'])
@sign_in_required
def update_profile(current_user):
    """
    Update profile route.
    """

    # parse the form
    form = UpdateProfileForm(request.form, obj=current_user)

    # render update profile form if GET request
    if request.method == 'GET':
        return render_template('user/update_profile.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/update_profile.html', form=form), 400

    # update the user information
    form.populate_obj(current_user)
    current_user.save()

    # make sure we store the avatar url in session
    session['avatar_url'] = current_user.avatar_url

    # notify the user
    flash('Profile successfully updated.', 'success')

    # redirect back to settings page
    return redirect(url_for('user.settings'))

@user.route('/update-password', methods=['GET', 'POST'])
@sign_in_required
def update_password(current_user):
    """
    Update password route.
    """

    # parse the form
    form = UpdatePasswordForm(request.form, user=current_user)

    # render update password form if GET request
    if request.method == 'GET':
        return render_template('user/update_password.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/update_password.html', form=form), 400

    # update password
    current_user.password = sha256_crypt.hash(form.new_password.data)
    current_user.save()

    # notify the user
    flash('Password successfully updated.', 'success')

    # redirect back to settings page
    return redirect(url_for('user.settings'))

@user.route('/delete', methods=['GET', 'POST'])
@sign_in_required
def delete(current_user):
    """
    Delete user route.
    """

    # render delete page if GET request
    if request.method == 'GET':
        return render_template('user/delete.html')

    current_user.delete()

    # make sure we clear the session
    session.clear()

    # notify user
    flash('Successfully deleted account.', 'success')

    # redirect back to homepage
    return redirect(url_for('home.index'))

@user.route('/<user_id>/posts', methods=['GET'])
@user_required
def posts(user_id, selected_user):
    """
    User posts route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for user's posts (making sure to exclude the actual content)
    results = get_posts(user_id=user_id,
                        exclude=['content'],
                        order_by=['-created'],
                        skip=skip,
                        limit=limit)

    return jsonify(serialize(results))

littleblog/templates/_formhelpers.html
{% macro render_field(field, show_label=True, top_help=None, bottom_help=None) %}
  <div class="form-group {{'has-error' if field.errors }}">
    {% if show_label %}
      {{ field.label(class_='control-label') }}
    {% endif %}
    {% if top_help %}
      <div class="help-block">
        {{ top_help | safe }}
      </div>
    {% endif %}
    {{ field(class_='form-control', **kwargs) | safe }}
    <div class="help-block with-errors">
      {% if bottom_help %}
        {{ bottom_help }}
      {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro render_form_errors(form) %}
  {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      <ul class="errors">
        {% for field_name, field_errors in form.errors.items() %}
          {% for error in field_errors %}
            <li>{{ form[field_name].label }}: {{ error }}</li>
          {% endfor %}
        {% endfor %}
      </ul>
    </div>
  {% endif %}
{% endmacro %}

littleblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>LittleBlog</title>
  <meta name="description" content="Read, write and comment on blog posts.">
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png') }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
  <link rel="mask-icon" href="{{ url_for('static', filename='safari-pinned-tab.svg') }}" color="#5bbad5">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <link rel="manifest" href="{{ url_for('static', filename='site.webmanifest') }}">
  <meta name="msapplication-config" content="{{ url_for('static', filename='browserconfig.xml') }}">
  <meta name="msapplication-TileColor" content="#00a300">
  <meta name="theme-color" content="#ffffff">
  <!-- bootstrap css -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE="
    crossorigin="anonymous">
  <!-- fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rozha+One">
  <!-- site css -->
  {% assets 'all_css' %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
</head>

<body class="{{ body_classes }}">
  <!-- navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header pull-left">
        <a class="navbar-brand" href="{{ url_for('home.index') }}">LittleBlog</a>
      </div>
      <div class="pull-right">
        <form class="search-form hidden-xs hidden-sm" action="{{ url_for('search.index') }}" method="get">
          <span class="search-btn glyphicon glyphicon-search" aria-hidden="true"></span>
          <input type="search" name="terms" class="form-control search-input collapsed" placeholder="Search LittleBlog" />
        </form>
        <a class="btn btn-link search-btn hidden-md hidden-lg" href="{{ url_for('search.index') }}">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </a>
        {% if session.user_id %}
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <img class="avatar" src="{{ session.avatar_url }}" alt="Avatar">
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <a href="{{ url_for('post.create') }}">New Post</a>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <a href="{{ url_for('user.show', user_id=session.user_id) }}">Profile</a>
              </li>
              <li>
                <a href="{{ url_for('user.settings') }}">Settings</a>
              </li>
              <li>
                <a href="{{ url_for('user.sign_out') }}" class="sign-out">Sign out</a>
              </li>
            </ul>
          </div>
        {% else %}
          <a class="btn btn-link" href="{{ url_for('user.sign_in') }}">Sign in</a>
          <a class="btn btn-primary" href="{{ url_for('user.sign_up') }}">Sign up</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-fluid page-container">
    <!-- flashes -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <!-- template content -->
    <div class="page">
      {% block content %}{% endblock %}
    </div>
  </div>

  <!-- jQuery -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <!-- jQuery dotdotdot -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery.dotdotdot/3.2.3/jquery.dotdotdot.js" integrity="sha256-n4myJMxAvCt19AC/KyEEn+W7DwBThTl2safyLWUsuDY=" crossorigin="anonymous"></script>
  <!-- bootstrap js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>
  <!-- bootstrap validator -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js" integrity="sha256-dHf/YjH1A4tewEsKUSmNnV05DDbfGN3g7NMq86xgGh8=" crossorigin="anonymous"></script>
  <!-- lodash js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js" integrity="sha256-7/yoZS3548fXSRXqc/xYzjsmuW3sFKzuvOCHd06Pmps=" crossorigin="anonymous"></script>
  <!-- site js -->
  {% assets 'all_js' %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
</body>

</html>