littleblog/blueprints/user.py
"""
Exports user routes.
"""

from flask import (Blueprint,
                   flash,
                   jsonify,
                   redirect,
                   render_template,
                   request,
                   session,
                   url_for)
from passlib.hash import sha256_crypt

from littleblog.forms import SignInForm, SignUpForm, UpdatePasswordForm, UpdateProfileForm
from littleblog.helpers import (get_posts,
                          serialize,
                          sign_in_required,
                          sign_out_required,
                          user_required)
from littleblog.models import User

user = Blueprint('user', __name__, url_prefix='/user')

"""
User routes.
"""

@user.route('/sign-up', methods=['GET', 'POST'])
@sign_out_required
def sign_up():
    """
    User sign up route.
    """

    # parse the form
    form = SignUpForm(request.form)

    # render sign up form if GET request
    if request.method == 'GET':
        return render_template('user/sign_up.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/sign_up.html', form=form), 400

    # save new user
    new_user = User(email=form.email.data,
                    password=sha256_crypt.hash(form.password.data),
                    display_name=form.display_name.data).save()

    # make sure we store user id and avatar url in session
    session['user_id'] = str(new_user.id)
    session['avatar_url'] = new_user.avatar_url

    # notify user
    flash('Profile successfully created.', 'success')

    # redirect to user's profile page
    return redirect(url_for('user.show', user_id=session['user_id']))

@user.route('/sign-in', methods=['GET', 'POST'])
@sign_out_required
def sign_in():
    """
    User sign in route.
    """

    # parse the form
    form = SignInForm(request.form)

    # render sign in form if GET request
    if request.method == 'GET':
        return render_template('user/sign_in.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/sign_in.html', form=form), 400

    # make sure we store user id and avatar url in session
    session['user_id'] = str(form.user.id)
    session['avatar_url'] = form.user.avatar_url

    # notify user
    flash('Successfully signed in.', 'success')

    # redirect to next screen (if there is one) or home page
    return redirect(request.args.get('next') or url_for('home.index'))

@user.route('/sign-out', methods=['GET', 'POST'])
def sign_out():
    """
    User sign out route.
    """

    # clear session data only if POST request
    if request.method == 'POST':
        session.clear()

    # render sign out page
    return render_template('user/sign_out.html')

@user.route('/<user_id>/show', methods=['GET'])
@user_required
def show(user_id, selected_user):
    """
    User show route.
    """

    return render_template('user/show.html', user=selected_user)

@user.route('/settings', methods=['GET'])
@sign_in_required
def settings(current_user):
    """
    User settings route.
    """

    return render_template('user/settings.html', user=current_user)

@user.route('/update-profile', methods=['GET', 'POST'])
@sign_in_required
def update_profile(current_user):
    """
    Update profile route.
    """

    # parse the form
    form = UpdateProfileForm(request.form, obj=current_user)

    # render update profile form if GET request
    if request.method == 'GET':
        return render_template('user/update_profile.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/update_profile.html', form=form), 400

    # update the user information
    form.populate_obj(current_user)
    current_user.save()

    # make sure we store the avatar url in session
    session['avatar_url'] = current_user.avatar_url

    # notify the user
    flash('Profile successfully updated.', 'success')

    # redirect back to settings page
    return redirect(url_for('user.settings'))

@user.route('/update-password', methods=['GET', 'POST'])
@sign_in_required
def update_password(current_user):
    """
    Update password route.
    """

    # parse the form
    form = UpdatePasswordForm(request.form, user=current_user)

    # render update password form if GET request
    if request.method == 'GET':
        return render_template('user/update_password.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/update_password.html', form=form), 400

    # update password
    current_user.password = sha256_crypt.hash(form.new_password.data)
    current_user.save()

    # notify the user
    flash('Password successfully updated.', 'success')

    # redirect back to settings page
    return redirect(url_for('user.settings'))

@user.route('/delete', methods=['GET', 'POST'])
@sign_in_required
def delete(current_user):
    """
    Delete user route.
    """

    # render delete page if GET request
    if request.method == 'GET':
        return render_template('user/delete.html')

    current_user.delete()

    # make sure we clear the session
    session.clear()

    # notify user
    flash('Successfully deleted account.', 'success')

    # redirect back to homepage
    return redirect(url_for('home.index'))

@user.route('/<user_id>/posts', methods=['GET'])
@user_required
def posts(user_id, selected_user):
    """
    User posts route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for user's posts (making sure to exclude the actual content)
    results = get_posts(user_id=user_id,
                        exclude=['content'],
                        order_by=['-created'],
                        skip=skip,
                        limit=limit)

    return jsonify(serialize(results))

littleblog/templates/user/delete.html
{% extends 'layout.html' %}

{% set body_classes='user delete' %}

{% block content %}
  <div class="text-center">
    <div class="form-header plain">
      <h1>Delete account</h1>
      This will delete your account, all blog posts and comments.
    </div>
    <form action="{{ url_for('user.delete') }}" method="post">
      <div class="form-group">
        <button class="btn btn-danger btn-block">
          Delete my account
        </button>
      </div>
      <div class="form-group">
        <a class="btn btn-default btn-block" href="{{ url_for('user.settings') }}">
          Back to settings
        </a>
      </div>
    </form>
  </div>
{% endblock %}

littleblog/templates/user/settings.html
{% extends 'layout.html' %}

{% set body_classes='user settings' %}

{% block content %}
  <div class="text-center">
    <div class="page-header plain">
      <h1>User settings</h1>
    </div>
    <div class="list-group">
      <a href="{{ url_for('user.update_profile') }}" class="list-group-item">
        <h2 class="list-group-item-heading">Update Profile</h2>
        <p class="list-group-item-text">Update display name, avatar and bio.</p>
      </a>
      <a href="{{ url_for('user.update_password') }}" class="list-group-item">
        <h2 class="list-group-item-heading">Update Password</h2>
        <p class="list-group-item-text">Update password for this account.</p>
      </a>
    </div>
    <div class="list-group">
      <a href="{{ url_for('user.delete') }}" class="list-group-item list-group-item-danger">
        <h2 class="list-group-item-heading">Delete Account</h2>
        <p class="list-group-item-text">Delete account and all of your content.</p>
      </a>
    </div>
    <a class="btn btn-default btn-block" href="{{ url_for('user.show', user_id=user.id) }}">
      Back to profile
    </a>
  </div>
{% endblock %}

littleblog/templates/user/show.html
{% extends 'layout.html' %}

{% set body_classes='user show' %}

{% block content %}
  <div class="row user-info">
    <div class="col-xs-7">
      <h1 class="display-name">{{ user.display_name }}</h1>
      {% if user.bio %}
        <p class="bio">{{ user.bio }}</p>
      {% endif %}
      <p class="created">Member since {{ user.created | format_date }}</p>
    </div>
    <div class="col-xs-5">
      <img class="avatar" src="{{ user.avatar_url }}">
    </div>
  </div>
  <hr>
  <div class="section-header">
    <h2>{{ user.display_name }}&apos;s posts</h2>
  </div>
  <div class="posts row"></div>
  <div class="text-center">
    <button type="button" class="load-more hidden btn btn-primary">Load more</button>
  </div>
{% endblock %}

littleblog/templates/user/sign_in.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field, render_form_errors %}

{% set body_classes='user sign-in' %}

{% block content %}
  <div class="form-header plain text-center">
    <h1>Sign in</h1>
  </div>
  {{ render_form_errors(form) }}
  <form data-toggle="validator" role="form" action="{{ url_for('user.sign_in', next=request.args.get('next', '')) }}" method="post">
    {{ form.csrf_token }}
    {{ render_field(form.email, type='email', required=True, data_error='Email address is invalid') }}
    {{ render_field(form.password, required=True) }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Sign in</button>
    </div>
  </form>
  <div class="text-center">
    Are you new to LittleBlog? <a class="link" href="{{ url_for('user.sign_up') }}">Sign up</a>.
  </div>
{% endblock %}

littleblog/templates/user/sign_out.html
{% extends 'layout.html' %}

{% set body_classes='user sign-out' %}

{% block content %}
  <div class="text-center">
    {% if session.user_id %}
      <div class="page-header plain text-center">
        <h1>Sign out</h1>
      </div>
      <p>
        To sign out of LittleBlog, please <a class="sign-out" href="{{ url_for('user.sign_out') }}">click here</a>.
      </p>
    {% else %}
      <div class="page-header plain text-center">
        <h1>You&apos;ve been signed out</h1>
      </div>
      <a class="btn btn-primary" href="{{ url_for('home.index') }}">
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
        LittleBlog home
      </a>
      <a class="btn btn-primary" href="{{ url_for('user.sign_in') }}">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        Sign in again
      </a>
    {% endif %}
  </div>
{% endblock %}

littleblog/templates/user/sign_up.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field, render_form_errors %}

{% set body_classes='user sign-up' %}

{% block content %}
  <div class="form-header plain text-center">
    <h1>Sign up</h1>
  </div>
  {{ render_form_errors(form) }}
  <form data-toggle="validator" role="form" action="{{ url_for('user.sign_up') }}" method="post">
    {{ form.csrf_token }}
    {{ render_field(form.email, type='email', required=True, data_error='Email address is invalid') }}
    {{ render_field(form.display_name, required=True, maxlength=50) }}
    {{ render_field(form.password, bottom_help='Minimum of 6 characters', required=True, data_minlength='6') }}
    {{ render_field(form.confirmation, required=True) }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Sign up</button>
    </div>
  </form>
  <div class="text-center">
    Already have an account? <a class="link" href="{{ url_for('user.sign_in') }}">Sign in</a>.
  </div>
{% endblock %}

littleblog/templates/user/update_password.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field, render_form_errors %}

{% set body_classes='user update-password' %}

{% block content %}
  <div class="form-header plain text-center">
    <h1>Update password</h1>
  </div>
  {{ render_form_errors(form) }}
  <form data-toggle="validator" role="form" action="{{ url_for('user.update_password') }}" method="post">
    {{ form.csrf_token }}
    {{ render_field(form.current_password, required=True) }}
    {{ render_field(form.new_password, bottom_help='Minimum of 6 characters', required=True, data_minlength='6') }}
    {{ render_field(form.confirmation, required=True) }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Update</button>
    </div>
    <div class="form-group">
      <a class="btn btn-default btn-block" href="{{ url_for('user.settings') }}">Back to settings</a>
    </div>
  </form>
{% endblock %}

littleblog/templates/user/update_profile.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field, render_form_errors %}

{% set body_classes='user update-profile' %}

{% block content %}
  <div class="form-header plain text-center">
    <h1>Update profile</h1>
  </div>
  {{ render_form_errors(form) }}
  <form data-toggle="validator" role="form" action="{{ url_for('user.update_profile') }}" method="post">
    {{ form.csrf_token }}
    {{ render_field(form.display_name, required=True, maxlength=50) }}
    {{ render_field(form.avatar_url, required=True, type='url') }}
    {{ render_field(form.bio, placeholder='Tell us a bit about yourself', maxlength=160, rows=3)}}
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Update</button>
    </div>
    <div class="form-group">
      <a class="btn btn-default btn-block" href="{{ url_for('user.settings') }}">Back to settings</a>
    </div>
  </form>
{% endblock %}