littleblog/blueprints/post.py
"""
Exports post routes.
"""

from datetime import datetime

from flask import (Blueprint,
                   flash,
                   jsonify,
                   redirect,
                   render_template,
                   request,
                   session,
                   url_for)

from littleblog.forms import CommentForm, PostForm
from littleblog.helpers import (author_required,
                          get_comments,
                          get_posts,
                          markdown_to_html,
                          post_required,
                          serialize,
                          sign_in_required)
from littleblog.models import Comment, Post

post = Blueprint('post', __name__, url_prefix='/post')

@post.route('/create', methods=['GET', 'POST'])
@sign_in_required
def create(current_user):
    """
    Create post route.
    """

    # parse the form
    form = PostForm(request.form, obj=Post())

    # render create post form if GET request
    if request.method == 'GET':
        return render_template('post/create.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('post/create.html', form=form), 400

    # create new post
    new_post = Post(author=current_user,
                    title=form.title.data,
                    lead_paragraph=form.lead_paragraph.data,
                    image_url=form.image_url.data,
                    content=form.content.data).save()

    # notify user
    flash('Post successfully created.', 'success')

    # redirect to post page
    return redirect(url_for('post.show', post_id=str(new_post.id)))

@post.route('/<post_id>/show', methods=['GET'])
@post_required
def show(post_id, selected_post):
    """
    Show post route.
    """

    return render_template('post/show.html',
                           form=CommentForm(),
                           post=selected_post,
                           is_author=str(selected_post.author.id) == session.get('user_id'))

@post.route('/<post_id>/settings', methods=['GET'])
@sign_in_required
@post_required
@author_required
def settings(current_user, post_id, selected_post):
    """
    Post settings route.
    """

    return render_template('post/settings.html', post=selected_post)

@post.route('/<post_id>/update', methods=['GET', 'POST'])
@sign_in_required
@post_required
@author_required
def update(current_user, post_id, selected_post):
    """
    Update post route.
    """

    # parse the form
    form = PostForm(request.form, obj=selected_post)

    # render update post form if GET request
    if request.method == 'GET':
        return render_template('post/update.html', form=form, post=selected_post)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('post/update.html', form=form, post=selected_post), 400

    # update the post information
    form.populate_obj(selected_post)
    selected_post.last_updated = datetime.now()
    selected_post.save()

    # notify the user
    flash('Post successfully updated.', 'success')

    # redirect back to post page
    return redirect(url_for('post.show', post_id=post_id))

@post.route('/<post_id>/delete', methods=['GET', 'POST'])
@sign_in_required
@post_required
@author_required
def delete(current_user, post_id, selected_post):
    """
    Delete post route.
    """

    # render delete page if GET request
    if request.method == 'GET':
        return render_template('post/delete.html', post=selected_post)

    selected_post.delete()

    # notify user
    flash('Successfully deleted post.', 'success')

    # redirect back to homepage
    return redirect(url_for('home.index'))

@post.route('/latest', methods=['GET'])
def latest():
    """
    Latest post route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for latest posts (making sure to exclude the actual content)
    results = get_posts(exclude=['content'],
                        order_by=['-created'],
                        skip=skip,
                        limit=limit)

    return jsonify(serialize(results))

@post.route('/<post_id>/comments', methods=['GET'])
@post_required
def comments(post_id, selected_post):
    """
    Post comments route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for post's comments (making sure to exclude the post itself)
    results = get_comments(post_id=post_id,
                           exclude=['post'],
                           order_by=['created'],
                           skip=skip,
                           limit=limit)

    return jsonify(serialize(results))

@post.route('/<post_id>/comment', methods=['POST'])
@sign_in_required
@post_required
def comment(current_user, post_id, selected_post):
    """
    Post comment route.
    """

    # parse the form
    form = CommentForm(request.form)

    # form is not valid so return error
    if not form.validate_on_submit():
        errors = []
        for field_name, field_errors in form.errors.items():
            for error in field_errors:
                errors.append(error)
        return jsonify({'errors': errors, 'success': False}), 400

    # create the comment
    Comment(author=current_user,
            post=selected_post,
            text=form.text.data).save()

    return jsonify({'success': True}), 200

@post.route('/preview', methods=['POST'])
def preview():
    """
    Post preview route.
    """

    return jsonify({'html': markdown_to_html(request.form.get('content', ''))}), 200

littleblog/blueprints/user.py
"""
Exports user routes.
"""

from flask import (Blueprint,
                   flash,
                   jsonify,
                   redirect,
                   render_template,
                   request,
                   session,
                   url_for)
from passlib.hash import sha256_crypt

from littleblog.forms import SignInForm, SignUpForm, UpdatePasswordForm, UpdateProfileForm
from littleblog.helpers import (get_posts,
                          serialize,
                          sign_in_required,
                          sign_out_required,
                          user_required)
from littleblog.models import User

user = Blueprint('user', __name__, url_prefix='/user')

"""
User routes.
"""

@user.route('/sign-up', methods=['GET', 'POST'])
@sign_out_required
def sign_up():
    """
    User sign up route.
    """

    # parse the form
    form = SignUpForm(request.form)

    # render sign up form if GET request
    if request.method == 'GET':
        return render_template('user/sign_up.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/sign_up.html', form=form), 400

    # save new user
    new_user = User(email=form.email.data,
                    password=sha256_crypt.hash(form.password.data),
                    display_name=form.display_name.data).save()

    # make sure we store user id and avatar url in session
    session['user_id'] = str(new_user.id)
    session['avatar_url'] = new_user.avatar_url

    # notify user
    flash('Profile successfully created.', 'success')

    # redirect to user's profile page
    return redirect(url_for('user.show', user_id=session['user_id']))

@user.route('/sign-in', methods=['GET', 'POST'])
@sign_out_required
def sign_in():
    """
    User sign in route.
    """

    # parse the form
    form = SignInForm(request.form)

    # render sign in form if GET request
    if request.method == 'GET':
        return render_template('user/sign_in.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/sign_in.html', form=form), 400

    # make sure we store user id and avatar url in session
    session['user_id'] = str(form.user.id)
    session['avatar_url'] = form.user.avatar_url

    # notify user
    flash('Successfully signed in.', 'success')

    # redirect to next screen (if there is one) or home page
    return redirect(request.args.get('next') or url_for('home.index'))

@user.route('/sign-out', methods=['GET', 'POST'])
def sign_out():
    """
    User sign out route.
    """

    # clear session data only if POST request
    if request.method == 'POST':
        session.clear()

    # render sign out page
    return render_template('user/sign_out.html')

@user.route('/<user_id>/show', methods=['GET'])
@user_required
def show(user_id, selected_user):
    """
    User show route.
    """

    return render_template('user/show.html', user=selected_user)

@user.route('/settings', methods=['GET'])
@sign_in_required
def settings(current_user):
    """
    User settings route.
    """

    return render_template('user/settings.html', user=current_user)

@user.route('/update-profile', methods=['GET', 'POST'])
@sign_in_required
def update_profile(current_user):
    """
    Update profile route.
    """

    # parse the form
    form = UpdateProfileForm(request.form, obj=current_user)

    # render update profile form if GET request
    if request.method == 'GET':
        return render_template('user/update_profile.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/update_profile.html', form=form), 400

    # update the user information
    form.populate_obj(current_user)
    current_user.save()

    # make sure we store the avatar url in session
    session['avatar_url'] = current_user.avatar_url

    # notify the user
    flash('Profile successfully updated.', 'success')

    # redirect back to settings page
    return redirect(url_for('user.settings'))

@user.route('/update-password', methods=['GET', 'POST'])
@sign_in_required
def update_password(current_user):
    """
    Update password route.
    """

    # parse the form
    form = UpdatePasswordForm(request.form, user=current_user)

    # render update password form if GET request
    if request.method == 'GET':
        return render_template('user/update_password.html', form=form)

    # render form again if submitted form is invalid
    if not form.validate_on_submit():
        return render_template('user/update_password.html', form=form), 400

    # update password
    current_user.password = sha256_crypt.hash(form.new_password.data)
    current_user.save()

    # notify the user
    flash('Password successfully updated.', 'success')

    # redirect back to settings page
    return redirect(url_for('user.settings'))

@user.route('/delete', methods=['GET', 'POST'])
@sign_in_required
def delete(current_user):
    """
    Delete user route.
    """

    # render delete page if GET request
    if request.method == 'GET':
        return render_template('user/delete.html')

    current_user.delete()

    # make sure we clear the session
    session.clear()

    # notify user
    flash('Successfully deleted account.', 'success')

    # redirect back to homepage
    return redirect(url_for('home.index'))

@user.route('/<user_id>/posts', methods=['GET'])
@user_required
def posts(user_id, selected_user):
    """
    User posts route.
    """

    # get query parameters
    skip = request.args.get('skip', 0, type=int)
    limit = request.args.get('limit', 12, type=int)

    # query for user's posts (making sure to exclude the actual content)
    results = get_posts(user_id=user_id,
                        exclude=['content'],
                        order_by=['-created'],
                        skip=skip,
                        limit=limit)

    return jsonify(serialize(results))

littleblog/templates/post/create.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field, render_form_errors %}

{% set body_classes='post create' %}

{% block content %}
  <div class="form-header plain text-center">
    <h1>New post</h1>
  </div>
  {{ render_form_errors(form) }}
  <ul class="nav nav-tabs">
    <li role="presentation" class="active">
      <a href="#edit-tab" id="edit-select" data-toggle="tab">Edit</a>
    </li>
    <li role="presentation">
      <a href="#preview-tab" id="preview-select" data-toggle="tab">Preview</a>
    </li>
  </ul>
  <form data-toggle="validator" role="form" action="{{ url_for('post.create') }}" method="post">
    {{ form.csrf_token }}
    <div class="tab-content clearfix">
      <div class="tab-pane active" id="edit-tab">
        {{ render_field(form.title, required=True, maxlength=160) }}
        {{ render_field(form.lead_paragraph, maxlength=500, placeholder='A brief introduction', rows=5) }}
        {{ render_field(form.image_url, required=True, type='url') }}
        {{ render_field(form.content, required=True, maxlength=10000, rows=15, 
          top_help='Can be styled using <a href=\'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet\'>markdown</a>.') }}
      </div>
      <div class="tab-pane" id="preview-tab" class="preview"></div>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Publish</button>
    </div>
  </form>
{% endblock %}

littleblog/templates/post/delete.html
{% extends 'layout.html' %}

{% set body_classes='post delete' %}

{% block content %}
<div class="text-center">
  <div class="form-header plain">
    <h1>Delete your post, &#8220;{{ post.title }}&#8221;?</h1>
  </div>
  <form action="{{ url_for('post.delete', post_id=post.id) }}" method="post">
    <div class="form-group">
      <button class="btn btn-danger btn-block">
        Delete post
      </button>
    </div>
    <div class="form-group">
      <a class="btn btn-default btn-block" href="{{ url_for('post.show', post_id=post.id) }}">
        Back to post
      </a>
    </div>
  </form>
</div>
{% endblock %}

littleblog/templates/post/settings.html
{% extends 'layout.html' %}

{% set body_classes='post settings' %}

{% block content %}
  <div class="text-center">
    <div class="page-header plain">
      <h1>Settings for your post, &#8220;{{ post.title }}&#8221;</h1>
    </div>
    <div class="list-group">
      <a href="{{ url_for('post.update', post_id=post.id) }}" class="list-group-item">
        <h2 class="list-group-item-heading">Update Post</h2>
        <p class="list-group-item-text">Make amendments to your post.</p>
      </a>
    </div>
    <div class="list-group">
      <a href="{{ url_for('post.delete', post_id=post.id) }}" class="list-group-item list-group-item-danger">
        <h2 class="list-group-item-heading">Delete Post</h2>
        <p class="list-group-item-text">Delete post and all comments left.</p>
      </a>
    </div>
    <a class="btn btn-default btn-block" href="{{ url_for('post.show', post_id=post.id) }}">
      Back to post
    </a>
  </div>
{% endblock %}

littleblog/templates/post/show.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field %}

{% set body_classes='post show' %}

{% block content %}
  <div class="post-info">
    <div class="wrapper">
      <a href="{{ url_for('user.show', user_id=post.author.id) }}">
        <img class="avatar" src="{{ post.author.avatar_url }}">
      </a>
    </div>
    <div class="wrapper">
      <a class="author-name" href="{{ url_for('user.show', user_id=post.author.id) }}">
        {{ post.author.display_name }}
      </a>
      {% if post.author.bio %}
        <span class="bio">
          {{ post.author.bio }}
        </span>
      {% endif %}
      <span class="date">{{ post.created | format_date }}
        {% if post.last_updated %}
          (last updated {{ post.last_updated | format_date }})
        {% endif %}
      </span>
    </div>
  </div>
  <h1>
    {% if is_author %}
      <small>
        <a href="{{ url_for('post.settings', post_id=post.id) }}">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
      </small>
    {% endif %}
    {{ post.title }}
  </h1>
  <p class="lead">{{ post.lead_paragraph }}</p>
  <img class="post-img" src="{{ post.image_url }}">
  {{ post.content | markdown_to_html | safe }}
  <div class="comment-section">
    <div class="section-header">
      <h2>Comments</h2>
    </div>
    {% if session.user_id %}
      <form class="comment-form" action="{{ url_for('post.comment', post_id=post.id) }}" method="post">
        {{ form.csrf_token }}
        {{ render_field(form.text, show_label=False, maxlength=500, rows=4, placeholder='Leave a comment ...') }}
        <div class="form-group">
          <button class="btn btn-primary btn-block">Send</button>
        </div>
      </form>
    {% else %}
      <strong><a href="{{ url_for('user.sign_in', next=url_for('post.show', post_id=post.id)) }}">Sign in</a>
        to leave a comment.</strong>
    {% endif %}
    <div class="comments row"></div>
    <div class="text-center">
      <button type="button" class="load-more-comments hidden btn btn-primary">Load more</button>
    </div>
  </div>
{% endblock %}

littleblog/templates/post/update.html
{% extends 'layout.html' %}

{% from '_formhelpers.html' import render_field, render_form_errors %}

{% set body_classes='post update' %}

{% block content %}
  <div class="form-header plain text-center">
    <h1>Update your post, &#8220;{{ post.title }}&#8221;</h1>
  </div>
  {{ render_form_errors(form) }}
  <ul class="nav nav-tabs">
    <li role="presentation" class="active">
      <a href="#edit-tab" id="edit-select" data-toggle="tab">Edit</a>
    </li>
    <li role="presentation">
      <a href="#preview-tab" id="preview-select" data-toggle="tab">Preview</a>
    </li>
  </ul>
  <form data-toggle="validator" role="form" action="{{ url_for('post.update', post_id=post.id) }}" method="post">
    {{ form.csrf_token }}
    <div class="tab-content clearfix">
      <div class="tab-pane active" id="edit-tab">
        {{ render_field(form.title, required=True, maxlength=160) }}
        {{ render_field(form.lead_paragraph, maxlength=500, placeholder='A brief introduction', rows=5) }}
        {{ render_field(form.image_url, required=True, type='url') }}
        {{ render_field(form.content, required=True, maxlength=10000, rows=15, 
          top_help='Can be styled using <a href=\'https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet\'>markdown</a>.') }}
      </div>
      <div class="tab-pane" id="preview-tab" class="preview"></div>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-block">Publish</button>
    </div>
    <div class="form-group">
      <a class="btn btn-default btn-block" href="{{ url_for('post.settings', post_id=post.id) }}">
        Back to settings
      </a>
    </div>
  </form>
{% endblock %}